version: '3.9'

services:
  database:
    image: "postgres:15"
    restart: always
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '1433:5432'
    container_name: "database"